// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  black: string;
  blue: string;
  root: string;
  small: string;
  wide: string;
  yellow: string;
}
export const cssExports: CssExports;
export default cssExports;
