// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'activeLink': string;
  'header': string;
  'headerContent': string;
  'headerContentLinks': string;
  'headerContentLogo': string;
}
export const cssExports: CssExports;
export default cssExports;
