// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  header: string;
  headerContent: string;
  headerContentLinks: string;
  headerContentLogo: string;
  selected: string;
}
export const cssExports: CssExports;
export default cssExports;
