// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  content: string;
  contentGrid: string;
  contentSearch: string;
  contentTitle: string;
  root: string;
  status: string;
}
export const cssExports: CssExports;
export default cssExports;
