// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  index: string;
  indexContent: string;
  indexContentBanner: string;
  indexContentButton: string;
  indexContentSubtitle: string;
  indexContentTitle: string;
}
export const cssExports: CssExports;
export default cssExports;
