// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'content': string;
  'contentButtonBox': string;
  'contentImage': string;
  'contentText': string;
  'root': string;
}
export const cssExports: CssExports;
export default cssExports;
